### **Anggota Kelompok :**
1. Muhammad Iqbal (103102400020)
2. Zahira Kayla Wardhani (103102400022)
3. Ivana Gabby Lauretta (103102400037)
4. Evelyna Angie (103102400040)

### **1. Karakteristik Data**

In [1]:
data_int = 10       # Karakter data dari integer yg isinya bilangan bulat
data_float = 3.14   # Karakter data dari float yg isinya bilangan desimal
data_str = "Python" # Karakter data dari string yg isinya teks/karakter
data_bool = True    # Karakter data dari boolean yg isinya logika (benar/salah)

print("Karakteristik data adalah sebagai berikut:")
print("1. Tipe data dari data_int:", type(data_int))
print("2. Tipe data dari data_float:", type(data_float))
print("3. Tipe data dari data_str:", type(data_str))
print("4. Tipe data dari data_bool:", type(data_bool))

Karakteristik data adalah sebagai berikut:
1. Tipe data dari data_int: <class 'int'>
2. Tipe data dari data_float: <class 'float'>
3. Tipe data dari data_str: <class 'str'>
4. Tipe data dari data_bool: <class 'bool'>


### **2. Tipe data**

In [2]:
array_int = [1, 2, 3, 4, 5]   # Elemennya bertipe integer (bilangan bulat)
array_float = [1.2, 3.4, 5.6] # Elemennya bertipe float (bilangan desimal)

print("Array Integer:", array_int)
print("Array Float:", array_float)

Array Integer: [1, 2, 3, 4, 5]
Array Float: [1.2, 3.4, 5.6]


### **3. Array dengan berbagai teknik**

In [3]:
# Array dari list biasa
angka = [1, 2, 3, 4, 5] # Membuat array (list) dengan cara langsung menuliskan elemen-elemen di dalam tanda kurung siku
print("Array dari list biasa:", angka)

# Array dengan nilai yang sama
nol = [0, 0, 0, 0, 0] # Membuat array yang semua elemennya bernilai sama yaitu 0
print("Array dengan semua elemen nol:", nol)

# Array urutan angka dengan perulangan
urutan = [] # Membuat array kosong dulu, lalu menggunakan perulangan for untuk mengisi angka dari 1 sampai 5 ke dalam array.
for i in range(1, 6):
    urutan.append(i)
print("Array dengan urutan angka 1 sampai 5:", urutan)

# Array dengan nilai acak sederhana
acak = [3, 1, 4, 2, 5] # Membuat array dengan urutan elemen yang tidak beraturan/acak
print("Array dengan nilai acak sederhana:", acak)

Array dari list biasa: [1, 2, 3, 4, 5]
Array dengan semua elemen nol: [0, 0, 0, 0, 0]
Array dengan urutan angka 1 sampai 5: [1, 2, 3, 4, 5]
Array dengan nilai acak sederhana: [3, 1, 4, 2, 5]


### **4. Membuat matriks (list di dalam list)**

In [4]:
matrix = [
    [1, 2, 3], # Baris pertama
    [4, 5, 6], # Baris kedua
    [7, 8, 9]  # Baris ketiga
]

print("Matriks 3x3:")
for row in matrix: # Mengambil setiap baris di dalam matriks
    print(row) # Akan menampilkan list baris tersebut

Matriks 3x3:
[1, 2, 3]
[4, 5, 6]
[7, 8, 9]


***Memanipulasi Matriks dan Operasi-Operasi Matriks***

Matriks adalah susunan angka atau ekspresi dalam baris dan kolom. Mereka adalah alat fundamental dalam berbagai bidang seperti matematika, fisika, dan ilmu komputer. Tiga operasi matriks dasar adalah penjumlahan, pengurangan, dan perkalian, masing-masing dengan aturan dan sifatnya sendiri.

**1. Penjumlahan Matriks**

Penjumlahan matriks dilakukan dengan menambahkan elemen-elemen yang berada di posisi yang sama. Operasi ini hanya bisa dilakukan pada matriks yang memiliki dimensi yang sama (jumlah baris dan kolom yang sama).

*Sifat:*
- Komunitatif: A + B = B + A
- Asosiatif: (A + B) + C = A + (B + C)

**2. Pengurangan Matriks**

Sama seperti penjumlahan, pengurangan matriks juga hanya bisa dilakukan pada matriks yang berdimensi sama. Operasi ini dilakukan dengan mengurangkan elemen-elemen yang bersesuaian.

*Sifat:*
- Tidak Komunitatif: A - B != B - A
- Asosiatif: (A - B) - C = A - (B - C)

**3. Perkalian Matriks**

Perkalian matriks lebih kompleks. Syaratnya adalah jumlah kolom matriks pertama harus sama dengan jumlah baris matriks kedua. Elemen pada matriks hasil adalah jumlah dari perkalian elemen-elemen baris matriks pertama dengan elemen-elemen kolom matriks kedua.

*Sifat:*
- Tidak Komunitatif: AB != BA
- Asosiatif: (AB)C = A(BC)
- Distributif: A(B + C) = AB + AC

**CONTOH**

In [5]:
# Import library NumPy
import numpy as np

# Buat matriks A dan B
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

# Penjumlahan Matriks
C = A + B
print("Hasil Penjumlahan A + B:")
print(C)

print("\n---")

# Pengurangan Matriks
D = A - B
print("Hasil Pengurangan A - B:")
print(D)

print("\n---")

# Perkalian Matriks
# Catatan: Gunakan operator @ atau fungsi np.dot() untuk perkalian matriks
E = A @ B
print("Hasil Perkalian A @ B:")
print(E)

print("\n---")

# Contoh perkalian matriks dengan dimensi berbeda
F = np.array([[1, 2, 3], [4, 5, 6]]) # Matriks 2x3
G = np.array([[7, 8], [9, 10], [11, 12]]) # Matriks 3x2

H = F @ G # Hasilnya akan menjadi matriks 2x2
print("Hasil Perkalian Matriks F (2x3) dan G (3x2):")
print(H)

Hasil Penjumlahan A + B:
[[ 6  8]
 [10 12]]

---
Hasil Pengurangan A - B:
[[-4 -4]
 [-4 -4]]

---
Hasil Perkalian A @ B:
[[19 22]
 [43 50]]

---
Hasil Perkalian Matriks F (2x3) dan G (3x2):
[[ 58  64]
 [139 154]]


***Array Multidimensi***

NumPy `(Numerical Python)`, sebuah library fundamental di Python yang sangat penting untuk komputasi numerik dan analisis data.

Inti dari NumPy adalah objek `ndarray` (N-dimensional array), sebuah struktur data yang lebih efisien dan cepat daripada `list` bawaan Python, terutama untuk operasi matematika dalam jumlah besar.

Untuk membuat array multidimensi, sintaks yang digunakan mirip dengan sintaks untuk membuat array satu dimensi, hanya saja perlu menuliskan elemen-elemen sesuai dimensi array. Berikut merupakan contoh:

In [6]:
import numpy as np

# Creating list

list_1 = [1, 2, 3]
list_2 = [5, 6, 7]
list_3 = [9, 10, 11]

# Creating numpy array
sample_array = np.array([list_1,
                         list_2,
                         list_3])

print("Numpy multi dimensional array in phyton\n",
      sample_array)

Numpy multi dimensional array in phyton
 [[ 1  2  3]
 [ 5  6  7]
 [ 9 10 11]]


***Indeks Elemen pada Array***

Dalam Python, "array" paling sering diwakili oleh list. Untuk menemukan indeks suatu elemen, Anda memiliki beberapa cara utama:

**1. Menggunakan Metode `.index()`**

Ini merupakan cara paling umum dan sederhana. Metode ini mencari kemunculan pertama dari elemen yang dicari dan mengembalikan indeksnya. Namun, jika elemen tidak ditemukan, metode ini akan memicu kesalahan (`ValueError`). Oleh karena itu, sebaiknya gunakan `try-except` untuk menanganin kasus tersebut.

**2. Menggunakan `for` loop dengan `enumarate()`**

Ini adalah metode yang lebih flexible. Fungsi `enumerate()` memungkinkan untuk mengulang (loop) sebuah list sambil melacak baik indeks maupun nilai dari setiap elemen secara bersamaan. Cara ini ideal jika ingin menemukan semua kemunculan dari suatu elemen, bukan hanya yang pertama.

**3. Menggunakan List Comprehension**

Ini adalah cara lebih ringkas dan "Pythonic" untuk melakukan hal yang sama seperti `for` loop, yaitu menemukan semua indeks dari elemen yang cocok.

**CONTOH**

In [9]:
# Contoh 1: Menggunakan metode .index()
# Ini hanya menemukan kemunculan pertama dan dapat menimbulkan error

my_list = ['apel', 'pisang', 'ceri', 'pisang']

# Mencari indeks 'ceri'
try:
    index_ceri = my_list.index('ceri')
    print(f"Indeks dari 'ceri' adalah: {index_ceri}")
except ValueError:
    print("'ceri' tidak ditemukan dalam list.")

# Mencari indeks 'pisang' (hanya akan mengembalikan yang pertama)
try:
    index_pisang = my_list.index('pisang')
    print(f"Indeks dari 'pisang' yang pertama adalah: {index_pisang}")
except ValueError:
    print("'pisang' tidak ditemukan dalam list.")

print("\n")

# Contoh 2: Menggunakan for loop dengan enumerate()
# Ini menemukan semua kemunculan

daftar_angka = [10, 20, 30, 20, 40, 20]
target_angka = 20
indeks_ditemukan = []

for indeks, nilai in enumerate(daftar_angka):
    if nilai == target_angka:
        indeks_ditemukan.append(indeks)

if indeks_ditemukan:
    print(f"Angka {target_angka} ditemukan pada indeks: {indeks_ditemukan}")
else:
    print(f"Angka {target_angka} tidak ditemukan.")

print("\n")

# Contoh 3: Menggunakan list comprehension (cara yang lebih ringkas)
# Ini juga menemukan semua kemunculan

daftar_warna = ['merah', 'hijau', 'biru', 'hijau', 'kuning']
target_warna = 'hijau'

indeks_list_comp = [i for i, x in enumerate(daftar_warna) if x == target_warna]

if indeks_list_comp:
    print(f"Warna '{target_warna}' ditemukan pada indeks: {indeks_list_comp}")
else:
    print(f"Warna '{target_warna}' tidak ditemukan.")

Indeks dari 'ceri' adalah: 2
Indeks dari 'pisang' yang pertama adalah: 1


Angka 20 ditemukan pada indeks: [1, 3, 5]


Warna 'hijau' ditemukan pada indeks: [1, 3]


### Mengimplementasikan Operasi Logika Matematika Menggunakan Boolean
Operasi logika matematika menggunakan boolean adalah proses perhitungan logis dengan nilai kebenaran yang hanya punya dua kemungkinan:

True (benar/1)
False (salah/0)

🔑 Jenis Operasi Boolean

AND (Konjungsi)

- Simbol: and atau ∧
- Hasil True hanya jika kedua nilai benar.
- Contoh: True ∧ True = True, lainnya False.

OR (Disjungsi)

- Simbol: or atau ∨
- Hasil True jika salah satu bernilai benar.
- Contoh: True ∨ False = True.

NOT (Negasi)

- Simbol: not atau ¬
- Membalik nilai.
- Contoh: ¬True = False.

XOR (Exclusive OR)

- Simbol: ^
- Hasil True jika hanya satu yang benar, bukan keduanya.
- Contoh: True ^ False = True, True ^ True = False.


In [10]:
# Variabel Boolean
A = True
B = False

print("A =", A)
print("B =", B)

print("A AND B =", A and B)   # Konjungsi
print("A OR B  =", A or B)    # Disjungsi
print("NOT A   =", not A)     # Negasi
print("A XOR B =", A ^ B)     # Eksklusif OR


A = True
B = False
A AND B = False
A OR B  = True
NOT A   = False
A XOR B = True


### Melakukan Operasi Aritmatika

Operator aritmatika digunakan untuk melakukan operasi matematika pada data. Operator aritmatika yang tersedia di Python meliputi:

Bentuk outputnya setelah tanda pagar

In [11]:
a = 10
b = 20

c = a + b  # c = 30 (Penjumlahan)
d = a - b  # d = -10 (Pengurangan)
e = a * b  # e = 200 (Perkalian)
f = a / b  # f = 0.5 (Pembagian)
g = a ** b # g = 100000000000 (Perpangkatan)
h = a % b  # h = 0 (Sisa bagi)
i = a // b # i = 0 (Pembagian bulat)    

### Elementwise Function

Elementwise function adalah fungsi atau operasi yang diterapkan pada setiap elemen dari suatu data (misalnya list, array, atau matriks) secara individual.
Artinya, perhitungan dilakukan satu per satu pada tiap elemen, bukan langsung ke keseluruhan data.

Di Python, biasanya menggunakan NumPy karena mendukung operasi elementwise dengan cepat.

In [12]:
import numpy as np

# Membuat array
a = np.array([1, 2, 3, 4, 5])
b = np.array([10, 20, 30, 40, 50])

print("Array a:", a)
print("Array b:", b)

# Operasi elementwise
print("\nPenjumlahan (a + b):", a + b)     # Elemen a ditambah elemen b
print("Perkalian (a * b):", a * b)        # Elemen a dikali elemen b
print("Pangkat (a ** 2):", a ** 2)        # Setiap elemen a dipangkat 2
print("Akar (sqrt(a)):", np.sqrt(a))      # Akar kuadrat tiap elemen a
print("Sinus (sin(a)):", np.sin(a))       # Sinus tiap elemen a


Array a: [1 2 3 4 5]
Array b: [10 20 30 40 50]

Penjumlahan (a + b): [11 22 33 44 55]
Perkalian (a * b): [ 10  40  90 160 250]
Pangkat (a ** 2): [ 1  4  9 16 25]
Akar (sqrt(a)): [1.         1.41421356 1.73205081 2.         2.23606798]
Sinus (sin(a)): [ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]


# **Melakukan Agregasi(Penggabungan) Beberapa Array**

Di Python, array berasal dari modul `array` dan hanya bisa menampung data dengan tipe yang sama.  
Ada beberapa cara untuk menggabungkan dua array:

### **1. Menggunakan `append()`**
Menambahkan elemen satu per satu dari array kedua ke array pertama menggunakan perulangan.

In [13]:
import array as arr

a = arr.array('i', [10, 20, 30])
b = arr.array('i', [40, 50, 60])

for i in range(len(b)):
   a.append(b[i])
print(a.tolist())

[10, 20, 30, 40, 50, 60]


### **2. Menggunakan Operator `+`**
Caranya dengan ubah dulu array ke list, gabungkan, lalu ubah lagi ke array.

In [14]:
import array as arr

a = arr.array('i', [10, 20, 30])
b = arr.array('i', [40, 50, 60])

x = a.tolist()
y = b.tolist()
z = x+y
a = arr.array('i', z)

print(a.tolist())

[10, 20, 30, 40, 50, 60]


### **3. Menggunakan `extend()`**
Langsung menambahkan semua elemen array lain tanpa perlu loop.

In [15]:
import array as arr

a = arr.array('i', [10, 20, 30])
b = arr.array('i', [40, 50, 60])

a.extend(b)
print(a.tolist())

[10, 20, 30, 40, 50, 60]


### **4. Menggunakan NumPy**
`np.concatenate()` digunakan untuk menyatukan dua atau lebih array.

In [16]:
import numpy as np

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

gabungan = np.concatenate((arr1, arr2))
print(gabungan)

[1 2 3 4 5 6]


In [17]:
print(np.sum(gabungan))    # jumlah total → 21
print(np.mean(gabungan))   # rata-rata → 3.5
print(np.min(gabungan))    # nilai terkecil → 1
print(np.max(gabungan))    # nilai terbesar → 6
print(np.median(gabungan)) # median → 3.5

21
3.5
1
6
3.5


# **Melakukan Operasi dengan Logika Himpunan**

### **1. Logika AND**

| Logika AND| Hasil |
| ----- | ----- |
| `True and True`| True  |
| `True and False`| False |
| `False and True`| False |
| `False and False`| False |

In [18]:
# AND → harus dua-duanya True
print(5 > 3 and 10 > 5) # True
print(5 > 3 and 2 > 5) # False

True
False


### **2. Logika OR**

| Logika OR | Hasil |
| ----- | ----- |
| `True or True`| True |
| `True or False`| True |
| `False or True`| True |
| `False or False`| False|

In [19]:
# OR → cukup salah satu True
print(5 > 3 or 2 > 5) # True
print(1 > 3 or 2 > 5) # False

True
False


### **3. Logika NOT**

|Logika NOT| Hasil |
| ---- | ----- |
| `not True` | False |
| `not False`| True |

In [20]:
# NOT → membalik nilai
print(not (5 > 3)) # False
print(not (2 > 5)) # True

False
True


# **Manipulasi Array**

Di Python, array dikenal dengan nama **list**. List bisa dianggap sebagai wadah yang menampung banyak data, dan kita bisa dengan mudah mengambil, mengubah, maupun memanipulasi isinya.

## **1. Membuat List**
Gunakan `array('tipe', [elemen])`.  
Contoh `'i'` artinya integer.

In [21]:
import array as arr

angka = arr.array('i', [10, 20, 30, 40])
print(angka.tolist())

[10, 20, 30, 40]


## **2. Mengakses Elemen**
Gunakan indeks (mulai dari 0) untuk mengambil elemen.

In [22]:
print(angka[0])  # elemen pertama
print(angka[2])  # elemen ketiga

10
30


## **3. Slicing (Mengiris)**
Gunakan `[start:end]` untuk mengambil sebagian elemen (end tidak termasuk).

In [23]:
print(angka[1:3].tolist())  # ambil elemen index 1 dan 2

[20, 30]


## **4. Menambah Elemen**
- `append()` → menambah di akhir  
- `insert()` → menambah di indeks tertentu  
- `extend()` → menambah banyak elemen sekaligus

In [24]:
angka.append(50)
print(angka.tolist())

angka.insert(1, 15)
print(angka.tolist())

angka.extend([60, 70])
print(angka.tolist())

[10, 20, 30, 40, 50]
[10, 15, 20, 30, 40, 50]
[10, 15, 20, 30, 40, 50, 60, 70]


## **5. Menghapus Elemen**
- `del` → hapus berdasarkan indeks  
- `pop()` → hapus & kembalikan elemen berdasarkan indeks  
- `remove()` → hapus berdasarkan nilai (hanya yang pertama)

In [25]:
angka.pop(0)     # hapus index 0
print(angka.tolist())

angka.remove(40) # hapus nilai 40
print(angka.tolist())

del angka[1]     # hapus index 1
print(angka.tolist())

[15, 20, 30, 40, 50, 60, 70]
[15, 20, 30, 50, 60, 70]
[15, 30, 50, 60, 70]
